services:
  minecraft:
    image: itzg/minecraft-server
    container_name: "67"
    mem_limit: 12g
    cpus: "3.0"
    ports:
      - "${PORT:-5000}:25565"
    environment:
      EULA: "TRUE"
      TYPE: "NEOFORGE"
      VERSION: "1.21.1"
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      MODRINTH_PROJECTS: |
        create
        create-aeronautics
        distanthorizons:beta
        tectonic
        terralith
        c2me-neoforge
      MEMORY: "12G"
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${RCON_PASSWORD}
    volumes:
      - ./data:/data
    restart: unless-stopped
